### ISSUE TITLE
feat: deploy

### ISSUE THREAD

**Issue by YuriScarbaci** [YuriScarbaci/ggj2023#9]

**Comment by doblesantos** [comment]
subi un archivo para deploy en github pages, necesita permisos para funcionar mientras los subi a vercel haciendo un fork es rapido de subir si te cuesta darle permisos podemos configurar un versel en 2 segundos desde este repo

**Comment by doblesantos** [comment]
para que funcione el comando npm run export no debe dar error

**Comment by YuriScarbaci** [comment]
Voy a encargarme de fixear el typescript en cuanto se mergean todos los PR

**Comment by YuriScarbaci** [comment]
we can close this,
  we got the deploy going thanks to @doblesantos !
 https://yuriscarbaci.github.io/ggj2023 can be seen here 
  this is deployed with "github actions" which triggers after every change in develop which is great! thx!
